package gkit.mongo

case class Set[A]($set: A)
case class Unset[A]($unset: A)
case class Exists[A]($exists: A)
case class ElemMatch[A]($elemMatch: A)
case class All[A]($all: A)

case class Project[A]($project: A)
case class Match[A]($match: A)
case class Redact[A]($redact: A)
case class Limit[A]($limit: A)
case class Skip[A]($skip: A)
case class Unwind[A]($unwind: A)
case class Group[A]($group: A)
case class Sort[A]($sort: A)
case class GeoNear[A]($geoNear: A)
case class Out[A]($out: A)

case class AddToSet[A]($addToSet: A)
case class First[A]($first: A)
case class Last[A]($last: A)
case class Max[A]($max: A)
case class Min[A]($min: A)
case class Avg[A]($avg: A)
case class Push[A]($push: A)
case class PushAll[A]($pushAll: A)
case class Pull[A]($pull: A)
case class PullAll[A]($pullAll: A)
case class Pop[A]($pop: A)
case class Sum[A]($sum: A)
case class Each[A]($each: A)
case class Slice[A]($slice: A)
case class Position[A]($position: A)

case class And[A]($and: A)
case class Or[A]($or: A)
case class Not[A]($not: A)
case class Nin[A]($nin: A)
case class In[A]($in: A)
case class Nor[A]($nor: A)

case class SetEquals[A]($setEquals: A)
case class SetIntersection[A]($setIntersection: A)
case class SetDifference[A]($setDifference: A)
case class SetUnion[A]($setUnion: A)
case class SetIsSubset[A]($setIsSubset: A)
case class AnyElementTrue[A]($anyElementTrue: A)
case class AllElementsTrue[A]($allElementsTrue: A)

case class Cmp[A]($cmp: A)
case class Eq[A]($eq: A)
case class Gt[A]($gt: A)
case class Gte[A]($gte: A)
case class Lt[A]($lt: A)
case class Lte[A]($lte: A)
case class Ne[A]($ne: A)

case class Add[A]($add: A)
case class Divide[A]($divide: A)
case class Mod[A]($mod: A)
case class Multiply[A]($multiply: A)
case class Subtract[A]($subtract: A)

case class Concat[A]($concat: A)
case class Substr[A]($substr: A)

case class StrCaseCmp[A]($strcasecmp: A)
case class ToLower[A]($toLower: A)
case class ToUpper[A]($toUpper: A)

case class Meta[A]($meta: A)

case class Size[A]($size: A)

case class Map[A]($map: A)
case class Let[A]($let: A)
case class Literal[A]($literal: A)

case class DayOfMonth[A]($dayOfMonth: A)
case class DayOfWeek[A]($dayOfWeek: A)
case class Year[A]($year: A)
case class Month[A]($month: A)
case class Week[A]($week: A)
case class Hour[A]($hour: A)
case class Minute[A]($minute: A)
case class Second[A]($second: A)
case class Millisecond[A]($millisecond: A)

case class Cond[A]($cond: A)
case class IfNull[A]($ifNull: A)
